apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: demo-app-build
spec:
  source:
    type: Git
    git:
      url: "https://github.com/someuser/demo-app.git"
  strategy:
    type: Docker
  output:
    to:
      kind: imageStreamTag
      name: demo-app:latest    